services:
  db:
    image: postgres:latest
    container_name: food_delivery_database
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  app:
    build:
      context: .
      target: dev
    container_name: food_delivery_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV:development
    depends_on:
      - db
    volumes:
      # Mount the source code to allow hot reloading with nodemon
      - ./src:/usr/src/app/src
      - ./.env:/usr/src/app/.env
    command: ["nodemon", "src/index.ts"]

volumes:
  postgres_data:
